### ISSUE TITLE
Any plan to fix the importer?

### ISSUE THREAD

**Issue by charlescao460** [genshin-wishes/genshin-wishes-api#9]
There's a way to extract auth key from local log:
https://gist.github.com/MadeBaruna/1d75c1d37d19eca71591ec8a31178235

**Comment by charlescao460** [comment]
Could you please let the community know if this project is still under maintenance (i.e. accepting PRs)?

**Comment by jvergerolle** [comment]
[How to import](http://hello.genshin-wishes.com/d/84-unable-to-authenticate-sync-wishes-november-23-24/1)

And yes, we still accept PR
